name: InfiniteIQ Consulting
favicon: null
layout_spectrum: 0.18375089252367616
typography_spectrum: 0.7009146884083748
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.8248961705248803
  lightness: 0.4128996217623353
  saturation: 0.9246274153701961
  rhythmicContrast: 0.725287799956277
purpose: []
