name: InfiniteIQ Consulting
favicon: null
layout_spectrum: 0.24497
typography_spectrum: 0.73829
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#bf1e2d'
    - '#6d6e71'
    - '#bdbec0'
    - '#000000'
    - '#ffffff'
  brandStrength: 0.8248961705248803
  lightness: 0.4128996217623353
  saturation: 0.9246274153701961
  rhythmicContrast: 0.725287799956277
purpose: []
